server:
  port: 7002
spring:
  application:
    name: SpringCloud-consomer-7002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
      
feign:
  hystrix:
    enabled: true