server:
  port: 9000
  
  
spring:
  application:
    name: SpringCloud-Zuul
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

      
zuul:
  prefix: /zhizhang  routes:    zhizhang:
      path: /zhizhang/**
      service-id: SpringCloud-Client